#shorter aliases
alias g='git'
alias gb='git branch'
alias gmv='git mv'
alias gr='git rebase'
alias gc='git commit'
alias gco='git checkout'
alias gca='git commit -a'
alias gp='git push'
alias gpf='git-force-push'
alias gl='git pull'
alias glr='git pull --rebase'
alias gm='git merge'
alias gs='git status -sb'
alias gd='git difftool'
alias ga='git add'
alias grm="git status | grep deleted | awk '{print \$3}' | xargs git rm"
alias gu="git undo"
alias gaa="git add -A"
alias gtt="git-track-remote"