#!/usr/bin/env zsh
#
# set up dotfiles

export PATH=".:./bin:$PATH"

cd "$(dirname "$0")/.."
DOTFILES_ROOT="$(pwd -P)"

set -e

# Ensure Xcode Command Line Tools are installed on macOS
if [[ "$(uname)" == "Darwin" ]]; then
  if ! xcode-select -p &>/dev/null; then
    dotlog "info" "installing Xcode Command Line Tools..."
    xcode-select --install
    echo "Press any key when the installation has completed."
    read -k 1 </dev/tty
  fi
fi

echo ''

setup_gitconfig () {
  if [[ ! -f git/gitconfig.local.symlink ]]; then
    dotlog "info" 'setup gitconfig'

    git_credential='cache'
    if [[ "$(uname)" == "Darwin" ]]; then
      git_credential='osxkeychain'
    fi

    dotlog "user" ' - What is your github author name?'
    read -r git_authorname </dev/tty
    dotlog "user" ' - What is your github author email?'
    read -r git_authoremail </dev/tty

    # Escape sed special characters in user input
    git_authorname_escaped="${git_authorname//\\/\\\\}"
    git_authorname_escaped="${git_authorname_escaped//\//\\/}"
    git_authorname_escaped="${git_authorname_escaped//&/\\&}"

    git_authoremail_escaped="${git_authoremail//\\/\\\\}"
    git_authoremail_escaped="${git_authoremail_escaped//\//\\/}"
    git_authoremail_escaped="${git_authoremail_escaped//&/\\&}"

    sed -e "s/AUTHORNAME/$git_authorname_escaped/g" -e "s/AUTHOREMAIL/$git_authoremail_escaped/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink

    dotlog "success" 'gitconfig'
  fi
}

link_file () {
  local src=$1 dst=$2
  local overwrite= backup= skip=
  local action=

  if [[ -e "$dst" ]]; then
    if [[ "$overwrite_all" != "true" && "$backup_all" != "true" && "$skip_all" != "true" ]]; then
      local currentSrc="$(readlink "$dst")"

      if [[ "$currentSrc" == "$src" ]]; then
        skip=true
      else
        dotlog "user" "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -k action </dev/tty

        case "$action" in
          o) overwrite=true ;;
          O) overwrite_all=true ;;
          b) backup=true ;;
          B) backup_all=true ;;
          s) skip=true ;;
          S) skip_all=true ;;
        esac
      fi
    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [[ "$overwrite" == "true" ]]; then
      rm -rf "$dst"
      dotlog "success" "removed $dst"
    fi

    if [[ "$backup" == "true" ]]; then
      mv "$dst" "${dst}.backup"
      dotlog "success" "moved $dst to ${dst}.backup"
    fi

    if [[ "$skip" == "true" ]]; then
      dotlog "success" "skipped $src"
    fi
  fi

  if [[ "$skip" != "true" ]]; then
    ln -s "$1" "$2"
    dotlog "success" "linked $1 to $2"
  fi
}

install_dotfiles () {
  dotlog "info" 'installing dotfiles'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $DOTFILES_ROOT/**/*.symlink(.); do
    [[ $src == */.git/* ]] && continue
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

setup_gitconfig
install_dotfiles

# If we're on a Mac, let's install and setup homebrew.
if [[ "$(uname)" == "Darwin" ]]; then
  dotlog "info" "installing dependencies"
  if source bin/dot; then
    dotlog "success" "dependencies installed"
  else
    dotlog "error" "error installing dependencies"
  fi
fi

dotlog "install" "Installing homebrew packages in a fresh shell session..."
zsh -lc "brew bundle --file=$HOME/.dotfiles/homebrew/Brewfile"