#!/bin/zsh
#
# Run all dotfiles installers.

set -e

cd "$DOTFILES"

# find the installers and run them iteratively
for installer in **/install.sh; do
  dotlog "install" "./${installer}"
  ./"${installer}"
done