#!/bin/zsh
#
# Run all dotfiles installers.

set -e

export DOTFILES="${DOTFILES:-$(cd "$(dirname "$0")/.." && pwd -P)}"

cd "$DOTFILES"

# find the installers and run them iteratively
for installer in **/install.sh; do
  dotlog "install" "./${installer}"
  if ! ./"${installer}"; then
    dotlog "error" "Failed: ./${installer}"
    exit 1
  fi
done